[build]
builder = "nixpacks"
buildCommand = "npm install --omit=dev && npm run build"
nixpacksPlan = """
[phases.setup]
nixPkgs = ['nodejs-22.12.0']
"""

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }