[build]
builder = "nixpacks"
buildCommand = "NODE_ENV=development npm ci && NODE_ENV=production npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 1